cmake_minimum_required(VERSION 3.23)
project(pointers C)

set(CMAKE_C_STANDARD 99)

add_executable(pointers main.c 01_pointer.c "02_swap two numbers .c" "03_change the value of constant integer.c" "04_print a string character by character.c" "05_count vowels and consonants.c" "06_read array elements and print the value with the addresses.c" "07_structure with pointer.c" "08_print sizes of different type of pointers .c" "09_double pointer.c" "10_ array of pointers.c" "11_Null pointer.c" "12_valid pointer as NULL pointer.c" "13_Modify value stored in other variable.c" pointer.c CreatingPointer.c ptr.c pointers.c)
